select distinct ID,STATUS,BILLING_STREET,BILLING_CITY,BILLING_STATE,BILLING_POSTAL_CODE,BILLING_COUNTRY,SHIPPING_STREET,SHIPPING_CITY,SHIPPING_STATE,SHIPPING_POSTAL_CODE,
SHIPPING_COUNTRY,current_timestamp() as Load_Time from "DEVELOPER_DB"."VIKAS_SCHEMA"."ORDER"

